---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/nubeliquida/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp page-400.html $DEPLOYPATH
    - /bin/cp page-403.html $DEPLOYPATH
    - /bin/cp page-404.html $DEPLOYPATH
    - /bin/cp page-500.html $DEPLOYPATH
    - /bin/cp page-503.html $DEPLOYPATH
    - /bin/cp sitemap_index.xml $DEPLOYPATH
    - /bin/cp -R /home3/nubeliquida/repositories/nubeliquida/repo/nube/contactform $DEPLOYPATH
    - /bin/cp -R /home3/nubeliquida/repositories/nubeliquida/repo/nube/css $DEPLOYPATH
    - /bin/cp -R /home3/nubeliquida/repositories/nubeliquida/repo/nube/fonts $DEPLOYPATH
    - /bin/cp -R /home3/nubeliquida/repositories/nubeliquida/repo/nube/img $DEPLOYPATH
    - /bin/cp -R /home3/nubeliquida/repositories/nubeliquida/repo/nube/js $DEPLOYPATH